# Hurricanes and Climate Change: A Bayesian approach
#### By: Madeline Abbott, Aidan Teppema, Daisy Cho
#### December 17, 2017


In the past summer, there were two major and devastating category 4 hurricanes in the US. Peoplel in Central America, Texas, Louisiana and other states lost their shelter and loved ones from Hurricane. Hurricane Irma soon after attacked as a ruining the coast of Florida. We wanted to see if this was indicative of the future and see if 

## The Datasets

To measure climate changes, we looked at four different data sets. The first data set is our main data set on hurricanes, provided by the homeland infrastructure foundation level data committee. This dataset recorded the hurricane’s wind speed, dates of occurrence, location, pressure, and the category of the hurricane. 
```{r}

```
Our indicator variables are temperature anomalies provided by NASA, CO2 provided by the national oceanic and atmospheric administration, and the North Atlantic Oscillation Index or NAOI which is provided by the national center for atmospheric research. 
The temperature anomalies are the difference from the temperature at the time from the baseline temperature, which is created from an average of 30 years of temperature data. 
NAOI is the fluctuations in the difference of atmospheric pressure at sea level (SLP) in the Northern Atlantic ocean.

## What is MCMC?

For all models we decided to run Markov chains to 

## Creating Our Models

### Hurricane Frequency

### Hurricane Windspeed

### Hurricane Duration


## Conclusion

## References
